const gombal = async (msg, text, mentions) => {
    let gombalan = [
        "Aku bukan tukang sapu, tapi hatiku terbang bersamamu.",
        "Aku bisa berhenti jadi penjahit, asalkan bisa jadi yang menjahit hatimu.",
        "Kamu ibarat WiFi, nyambungin hatiku yang selalu offline.",
        "Kalau cinta itu boleh minta kembalian, aku minta kamu jadi milikku.",
        "Aku bukan tukang ojek, tapi hatiku terus mengantar cintaku padamu.",
        "Kamu bukan angin, tapi selalu membuatku terbang melayang.",
        "Seandainya kamu matematika, kamu pasti rumus cinta yang sulit aku pecahkan.",
        "Kamu kayak kamera, setiap senyummu selalu berhasil memotret hatiku.",
        "Aku bukan petugas parkir, tapi hatiku terasa nyaman saat ada di dekatmu.",
        "Kamu kayak kunci ingatan, terus ada di pikiranku setiap saat.",
        "Aku mau jadi lenteramu, biar kamu yang terang, dan aku yang terbakar.",
        "Cinta itu kayak nasi goreng, enaknya kalau kamu yang jadi bumbunya.",
        "Kamu bukan dokter gigi, tapi senyumanmu bisa sembuhkan hatiku yang sakit.",
        "Aku kayak kulkas, karena nggak bisa lepas darimu.",
        "Kamu kayak bintang, seringkali jadi penuntun hatiku di malam yang gelap.",
        "Kamu kayak tinta, tanpa kamu hidupku tak berwarna.",
        "Kalau rindu itu makanan, aku udah kekenyangan gara-gara kamu.",
        "Kamu kayak sepatu, nyaman dipakai dan tak pernah lepas dari langkahku.",
        "Aku bukan supir taksi, tapi hatiku selalu buatmu nyaman saat di sampingku.",
        "Kamu kayak musim hujan, bikin hatiku adem dan segar.",
        "Kamu kayak bunga, selalu mekar di hatiku.",
        "Aku bukan meteorologi, tapi aku bisa meramalkan cinta kita: cerah bersamamu.",
        "Kamu kayak puzzle, lengkapkan hidupku yang tak sempurna.",
        "Aku bukan pelaut, tapi kamu adalah bintang pengarah dalam hidupku.",
        "Kamu kayak kunci, membuka hatiku yang terkunci.",
        "Aku bukan chef, tapi aku bisa membuat hatimu leleh dengan cintaku.",
        "Kamu kayak magnet, selalu menarik perhatianku.",
        "Aku bukan peramal, tapi aku yakin masa depanku ada di sisimu.",
        "Kamu bukan pensil, tapi tanpamu hidupku tak bisa digambar.",
        "Aku kayak bulan, tak pernah lepas dari bayang-bayang cintamu.",
        "Kamu kayak kacamata, bikin pandanganku lebih indah.",
        "Aku bukan penguasa dunia, tapi hatiku telah kau taklukkan.",
        "Kamu kayak es krim, meski dingin tapi selalu bikin hatiku meleleh.",
        "Aku bukan musikus, tapi hatiku berdendang saat dekat denganmu.",
        "Kamu kayak pahlawan, selalu menyelamatkan hari-hariku.",
        "Aku bukan penari, tapi hatiku selalu berjoget saat bersamamu.",
        "Kamu kayak tomat, semakin lama semakin bikin hatiku merah padam.",
        "Aku bukan ahli biologi, tapi aku tahu kamu adalah DNA-ku.",
        "Kamu kayak jam dinding, setiap detik selalu berharga di sampingmu.",
        "Aku bukan sopir bus, tapi aku bisa mengantarmu ke bahagiaan.",
        "Kamu kayak bantal, bikin hidupku nyaman dan tenang.",
        "Aku bukan petani, tapi hatiku selalu ditanami cinta padamu.",
        "Kamu kayak balon udara, membuat hatiku terbang tinggi.",
        "Aku bukan arsitek, tapi hatiku sudah direncanakan untukmu.",
        "Kamu kayak air, memberi kehidupan pada setiap tetesan cintamu.",
        "Aku bukan jaring laba-laba, tapi kamu membuatku terjerat cinta.",
        "Kamu kayak hujan, selalu bikin hatiku basah kuyup.",
        "Aku bukan detektif, tapi aku terus mencari alasan untuk mencintaimu.",
        "Kamu kayak kunci, membuka pintu hatiku yang terkunci.",
        "Aku bukan tukang kebun, tapi hatiku selalu ditanami rindu padamu.",
        "Kamu kayak magnet, selalu menarik perhatian dan cintaku.",
        "Aku bukan seniman, tapi hatiku adalah kanvas untuk lukisan cintamu.",
        "Kamu kayak koin, membuat hidupku lebih berarti.",
        "Aku bukan ahli bedah, tapi kamu berhasil mengoperasi hatiku.",
        "Kamu kayak pelangi, mewarnai hidupku dengan kebahagiaan.",
        "Aku bukan ilmuwan, tapi kamu adalah penemuan terbaikku.",
        "Kamu kayak bintang jatuh, berhasil merebut hatiku dalam sekejap.",
        "Aku bukan pilot, tapi aku ingin terbang bersamamu ke dunia cinta.",
        "Kamu kayak matahari, menerangi kegelapan dalam hidupku.",
        "Aku bukan pembuat jam, tapi waktu terasa berhenti saat bersamamu.",
        "Aku bukan detektif, tapi hatiku berhasil memecahkan misteri cintamu.",
        "Kamu kayak senyum, membuat hari-hariku selalu cerah.",
        "Aku bukan penulis novel, tapi cerita cintaku hanya bisa ku tulis untukmu.",
        "Kamu kayak baju favorit, bikin aku selalu ingin memelukmu.",
        "Aku bukan penjual bunga, tapi hatiku mekar saat bersamamu.",
        "Kamu kayak kamera, setiap kali ada di dekatku, hatiku selalu ingin diabadikan.",
        "Aku bukan ahli kimia, tapi cintaku padamu reaksinya tak terduga.",
        "Kamu kayak mawar, selalu membuat hidupku berbunga-bunga.",
        "Aku bukan penyanyi, tapi hatiku selalu bernyanyi saat melihat senyumanmu.",
        "Kamu kayak pemandangan indah, sulit untuk ku lewatkan.",
        "Aku bukan penyihir, tapi kamu membuat hidupku terasa ajaib.",
        "Kamu kayak air minum, aku nggak bisa hidup tanpamu.",
        "Aku bukan pilot, tapi kamu adalah penerbang cintaku.",
        "Kamu kayak matahari terbit, membawa sinar kebahagiaan dalam hidupku.",
        "Aku bukan guru matematika, tapi cintaku padamu tak pernah berkurang.",
        "Kamu kayak hadiah ulang tahun, selalu membuatku berdebar-debar.",
        "Aku bukan petani, tapi hatiku selalu menghasilkan cinta untukmu.",
        "Kamu kayak cahaya bulan, selalu menerangi malamku yang sepi.",
        "Aku bukan penyanyi dangdut, tapi cintaku padamu seirama seperti musik dangdut.",
        "Kamu kayak permen karet, bikin hatiku melekat padamu."
    ]
    const chat = await msg.getChat();
    const randomIndex = Math.floor(Math.random() * gombalan.length);
    console.log(gombalan[randomIndex]);
    await chat.sendMessage(`*Gombalan buat* ${ text }\n\n${ gombalan[randomIndex] }`, { mentions });
}

module.exports = {
    gombal
}